# Generated by Django 4.0.3 on 2022-04-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='reports/covers/'),
        ),
    ]
