# Generated by Django 4.0.3 on 2022-04-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_report_isupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='isUpdated',
            field=models.BooleanField(default=False),
        ),
    ]
