# Generated by Django 4.0.3 on 2022-04-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_report_isviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='isViewed',
            field=models.BooleanField(default=False),
        ),
    ]
