# Generated by Django 4.0.3 on 2022-04-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_report_isviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='viewers',
            field=models.IntegerField(default=0),
        ),
    ]
